name: example
description: A new Flutter package.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite_entities_annotations:
    git:
      ref: master
      url: git@github.com:guid-empty/sqflite_entities_annotations.git

  sqflite_entities:
    git:
      ref: master
      url: git@github.com:guid-empty/sqflite_entities.git

  sqflite: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.1
  source_gen: ^1.0.0
  analyzer: ^4.7.0
  build: ^2.0.0
  flutter_lints: ^2.0.1
  sqflite_entities_generator:
    git:
      ref: master
      url: git@github.com:guid-empty/sqflite_entities_generator.git

flutter:
  uses-material-design: true