name: sqflite_entities
description: ORM approach to work with sqflite packages that would allow you to get some ORM practices out of the box for working with classes in the code
version: 0.0.2
homepage: https://github.com/guid-empty/sqflite_entities

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  build_runner: ^2.2.0
  source_gen: ^1.0.0
  analyzer: ^4.3.1
  build: ^2.0.0
  sqflite: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  test:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.3.2
  sqflite_common_ffi: ^2.1.1+1
  sqflite_entities_generator: ^0.0.1

