name: sqflite_entities
description: sqflite_entities_annotations
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  build_runner: ^2.2.0
  source_gen: ^1.0.0
  analyzer: ^4.3.1
  build: ^2.0.0
  sqflite_entities_annotations:
    path: ./../sqflite_entities_annotations
  sqflite: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
