targets:
  $default:
    builders:
      sqflite_entities:
        enabled: true

builders:
  sqflite_entities|sqflite_entities:
    import: "package:sqflite_entities/builder.dart"
    builder_factories: ["getBuilder"]
    build_extensions: {".dart": [".sql.g.dart"]}
    auto_apply: root_package
    build_to: source